services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.0
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-data:/opt/keycloak/data/h2
